let roommateData = [
    {
      name: 'Isabella Daniels',
      age: 28,
      isSmoker: false,
      hasPets: true,
      maxBudget: 3450,
      gender: 'non-binary',
      image: 'https://images.unsplash.com/photo-1530047198515-516ff90fc4d9?q=80&w=2574&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 1,
      bio: "Hi, I'm Isabella, a healthcare hero providing compassionate care in the bustling city of San Francisco. Beyond the hospital walls, I'm exploring local farmers' markets or unwinding with a good book in hand. My workspace is an oasis of tranquility amidst the vibrant energy of the city, reflecting the peace and healing I strive to bring to my patients.",
      important: "My foot is currently broken so it is important to me to find a place with an elevator."
    },
    {
      name: 'Bob Moore',
      age: 39,
      isSmoker: false,
      hasPets: true,
      maxBudget: 4579,
      gender: 'male',
      image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 2,
      bio: "Hey, I'm Bob, a tech enthusiast driving innovation in the tech hub of San Francisco. When I'm not coding, I'm hiking through redwood forests or capturing stunning aerial shots with my drone. In the digital realm, my workspace is a sanctuary of creativity, where lines of code converge to shape the future of technology.",
      important: "My foot is currently broken so it is important to me to find a place with an elevator."
    },
    {
      name: 'Sammy Taylor',
      age: 42,
      isSmoker: false,
      hasPets: true,
      maxBudget: 2139,
      gender: 'non-binary',
      image: 'https://images.unsplash.com/photo-1536426694225-d9c33045c03d?q=80&w=1287&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 3,
      bio: "Hey there, I'm Sammy, a nature lover embracing the rugged beauty of the Rocky Mountains from my home in Denver. When I'm not hitting the slopes, I'm hiking through scenic trails or camping beneath starry skies. My cozy cabin is a sanctuary amidst the majestic mountains, where every sunrise brings a new adventure and every sunset paints the sky in hues of gold.",
      important: "Having in-unit washer and dryer is a must for me, as well as dishwasher and either a parking garage or in an area with street parking for my car."
    },
    {
      name: 'Kyle Izzie',
      age: 39,
      isSmoker: true,
      hasPets: true,
      maxBudget: 3209,
      gender: 'male',
      image: 'https://images.unsplash.com/photo-1611403119860-57c4937ef987?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 4,
      bio: "Greetings, I'm Kyle, a fitness enthusiast staying active amidst Denver's breathtaking landscapes. When I'm not hitting the trails, I'm practicing yoga in city parks or cycling along scenic routes. My home gym is a sanctuary of strength and resilience, where every workout fuels my passion for health and wellness in the Mile High City.",
      important: "I have two cats that are partially out-door so a place with a backyard is ideal, also they are not dog friendly - so no one with dogs please!"
    },
    {
      name: 'Charlie Brown',
      age: 42,
      isSmoker: false,
      hasPets: true,
      maxBudget: 4011,
      gender: 'male',
      image: 'https://images.unsplash.com/photo-1487309078313-fad80c3ec1e5?q=80&w=2648&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 5,
      bio: "Hey, I'm Charles, Charlies for short, a tech enthusiast driving innovation in the tech hub of San Francisco. When I'm not coding, I'm hiking through redwood forests or capturing stunning aerial shots with my drone. In the digital realm, my workspace is a sanctuary of creativity, where lines of code converge to shape the future of technology.",
      important: "I have a chronic illness, so I would prefer a very clean roommate and to not have guests constantly over because I have a compromised immune system"
    },
    {
      name: 'Greyson Windle',
      age: 18,
      isSmoker: true,
      hasPets: false,
      maxBudget: 1135,
      gender: 'male',
      image: 'https://images.unsplash.com/photo-1525665363629-cdf85a703b50?q=80&w=1827&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 6,
      bio: "Hi, I'm Greyson, a music aficionado spreading rhythm and melody in the lively music scene of San Francisco. When I'm not strumming guitar chords, I'm exploring record stores or attending live performances in iconic venues. My studio is a symphony of sound amidst the city's cultural diversity, where melodies take shape and harmonies fill the air with musical magic.",
      important: "My foot is currently broken so it is important to me to find a place with an elevator."
    },
    {
      name: 'Jenny Dayton',
      age: 37,
      isSmoker: false,
      hasPets: false,
      maxBudget: 3218,
      gender: 'female',
      image: 'https://images.unsplash.com/photo-1530785602389-07594beb8b73?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 7,
      bio: "Hey, I'm Jen, an outdoor adventurer exploring the boundless wilderness surrounding Denver. Beyond hiking and camping, I'm rock climbing in rugged canyons or whitewater rafting down rushing rivers. In the heart of Colorado's outdoor playground, my basecamp is a haven of adventure, where every expedition is an opportunity to connect with nature and push my limits.",
      important: "Having in-unit washer and dryer is a must for me, as well as dishwasher and either a parking garage or in an area with street parking for my car."
    },
    {
      name: 'Alice Johnson',
      age: 23,
      isSmoker: false,
      hasPets: true,
      maxBudget: 3387,
      gender: 'non-binary',
      image: 'https://images.unsplash.com/photo-1520423465871-0866049020b7?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 8,
      bio: "Hi, I'm Alice, a healthcare hero providing compassionate care in the bustling city of San Francisco. Beyond the hospital walls, I'm exploring local farmers' markets or unwinding with a good book in hand. My workspace is an oasis of tranquility amidst the vibrant energy of the city, reflecting the peace and healing I strive to bring to my patients.",
      important: "I have two cats that are partially out-door so a place with a backyard is ideal, also they are not dog friendly - so no one with dogs please!"
    },
    {
      name: 'Mia Black',
      age: 23,
      isSmoker: false,
      hasPets: false,
      maxBudget: 2388,
      gender: 'non-binary',
      image: 'https://images.unsplash.com/photo-1491349174775-aaafddd81942?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 9, 
      bio: "Hello, I'm Mia, a fashionista crafting unique styles in the eclectic fashion scene of San Francisco. Beyond the runway, I'm exploring art galleries or dancing to live music in trendy venues. My studio is a canvas of creativity amidst the city's artistic spirit, where fabrics and colors intertwine to create fashion statements that reflect the vibrant energy of San Francisco.",
      important: "I would much prefer a place that has a gym in unit and separate bathrooms if possible!"
    },
    {
      name: 'Erin Maynor',
      age: 43,
      isSmoker: false,
      hasPets: false,
      maxBudget: 4358,
      gender: 'non-binary',
      image: 'https://images.unsplash.com/photo-1525186402429-b4ff38bedec6?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 10,
      bio: "Hi, I'm Erin, a history buff delving into Denver's rich heritage and storied past. When I'm not visiting museums or historic sites, I'm attending cultural events or exploring vintage neighborhoods. In the heart of the Mile High City, my home office is a portal to the past, where every artifact and archive tells a tale of Denver's fascinating history.",
      important: "I work very early in the mornings, so I would like to live with someone who goes to bed early/is on a similar schedule so we don’t keep eachother up at night or wake each other up in the morning."
    },
    {
      name: 'Anya Smith',
      age: 35,
      isSmoker: true,
      hasPets: false,
      maxBudget: 1112,
      gender: 'female',
      image: 'https://images.unsplash.com/photo-1633100533867-2ec15e9a3e1f?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 11,
      bio: "Hey, I'm Anya, a literature lover spinning tales in the charming neighborhoods of San Francisco. Beyond writing, I'm strolling through historic streets or sipping artisanal coffee in cozy cafes. In the comfort of my home office, books line the shelves, inspiring creativity and igniting imaginations with every turn of the page.",
      important: "I would much prefer a place that has a gym in unit and separate bathrooms if possible!"
    },
    {
      name: 'Kayla Smith',
      age: 30,
      isSmoker: true,
      hasPets: true,
      maxBudget: 2648,
      gender: 'non-binary',
      image: 'https://plus.unsplash.com/premium_photo-1661775820832-f971657b13f6?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 12,
      bio: "Hi, I'm Kayla, an aspiring artist capturing the vibrant colors of Denver's urban landscape on canvas. Beyond my studio, I'm exploring art districts or attending gallery openings to soak in the city's creative energy. In the heart of Denver's art scene, my workspace is a canvas of possibilities, where every brushstroke tells a story of inspiration and imagination.",
      important: "I have two cats that are partially out-door so a place with a backyard is ideal, also they are not dog friendly - so no one with dogs please!"
    },
    {
      name: 'Halle Harper',
      age: 32,
      isSmoker: true,
      hasPets: true,
      maxBudget: 1774,
      gender: 'female',
      image: 'https://images.unsplash.com/photo-1496360864286-5dbec8933908?q=80&w=1587&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 13,
      bio: "Hi, I'm Halle, a history buff delving into Denver's rich heritage and storied past. When I'm not visiting museums or historic sites, I'm attending cultural events or exploring vintage neighborhoods. In the heart of the Mile High City, my home office is a portal to the past, where every artifact and archive tells a tale of Denver's fascinating history.",
      important: "I have two cats that are partially out-door so a place with a backyard is ideal, also they are not dog friendly - so no one with dogs please!"
    },
    {
      name: 'Olivia Miller',
      age: 25,
      isSmoker: false,
      hasPets: false,
      maxBudget: 1389,
      gender: 'female',
      image: 'https://images.unsplash.com/photo-1531927557220-a9e23c1e4794?q=80&w=2187&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 14,
      bio: "Hello, I'm Olivia, a fitness fanatic sculpting bodies and minds in the urban landscape of San Francisco. When I'm not leading workout sessions, I'm catching waves along the California coast or indulging in healthy cooking experiments. My gym is a temple of vitality amidst the city's hustle and bustle, where sweat and determination converge to forge stronger, healthier lives.",
      important: "Having in-unit washer and dryer is a must for me, as well as dishwasher and either a parking garage or in an area with street parking for my car."
    },
    {
      name: 'Sandra McConnell',
      age: 42,
      isSmoker: true,
      hasPets: false,
      maxBudget: 4269,
      gender: 'female',
      image: 'https://images.unsplash.com/photo-1620052800096-e2861f0e1e3d?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 15,
      bio: "Hey, I'm Sandra, an outdoor adventurer exploring the boundless wilderness surrounding Denver. Beyond hiking and camping, I'm rock climbing in rugged canyons or whitewater rafting down rushing rivers. In the heart of Colorado's outdoor playground, my basecamp is a haven of adventure, where every expedition is an opportunity to connect with nature and push my limits.",
      important: "I work very early in the mornings, so I would like to live with someone who goes to bed early/is on a similar schedule so we don’t keep eachother up at night or wake each other up in the morning."
    },
    {
      name: 'Alice Moore',
      age: 47,
      isSmoker: false,
      hasPets: true,
      maxBudget: 3004,
      gender: 'female',
      image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 16,
      bio: "Hello, I'm Alice, a fitness fanatic sculpting bodies and minds in the urban landscape of San Francisco. When I'm not leading workout sessions, I'm catching waves along the California coast or indulging in healthy cooking experiments. My gym is a temple of vitality amidst the city's hustle and bustle, where sweat and determination converge to forge stronger, healthier lives.",
      important: "I have a dog so I need a pet friendly building, or better yet, a place with a backyard. She is super sweet and well behaved and loves to play, just needs more space!"
    },
    {
      name: 'Jacklyn Fall',
      age: 40,
      isSmoker: true,
      hasPets: false,
      maxBudget: 2199,
      gender: 'female',
      image: 'https://images.unsplash.com/photo-1572707691717-d1e37962423a?q=80&w=1287&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 17,
      bio: "Hi, I'm Jackie, a history buff delving into Denver's rich heritage and storied past. When I'm not visiting museums or historic sites, I'm attending cultural events or exploring vintage neighborhoods. In the heart of the Mile High City, my home office is a portal to the past, where every artifact and archive tells a tale of Denver's fascinating history.",
      important: "I work night shifts and need to sleep during the day so I would prefer someone that can be quiet during the day."
    },
    {
      name: 'Tayla Andrews',
      age: 25,
      isSmoker: false,
      hasPets: false,
      maxBudget: 2725,
      gender: 'non-binary',
      image: 'https://images.unsplash.com/photo-1527565290982-018bcfdbee74?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 18,
      bio: "Hi, I'm Tay, a history buff delving into Denver's rich heritage and storied past. When I'm not visiting museums or historic sites, I'm attending cultural events or exploring vintage neighborhoods. In the heart of the Mile High City, my home office is a portal to the past, where every artifact and archive tells a tale of Denver's fascinating history.",
      important: "I work very early in the mornings, so I would like to live with someone who goes to bed early/is on a similar schedule so we don’t keep eachother up at night or wake each other up in the morning."
    },
    {
      name: 'Nate Blake',
      age: 30,
      isSmoker: true,
      hasPets: false,
      maxBudget: 4508,
      gender: 'male',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 19,
      bio: "What's up, I'm Nate, an adventure seeker exploring the rugged terrain of the Pacific Northwest from my home base in San Francisco. When I'm not scaling mountains, I'm kayaking through picturesque bays or camping beneath starlit skies. My workspace is wherever the trail leads, a testament to the boundless spirit of exploration that drives me forward.",
      important: "I work very early in the mornings, so I would like to live with someone who goes to bed early/is on a similar schedule so we don’t keep eachother up at night or wake each other up in the morning."
    },
    {
      name: 'Jack Willett',
      age: 47,
      isSmoker: true,
      hasPets: false,
      maxBudget: 3615,
      gender: 'male',
      image: 'https://images.unsplash.com/photo-1504199367641-aba8151af406?q=80&w=2574&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 20,
      bio: "Hello, I'm Jack, an animal lover volunteering at Denver's local shelters and rescues to give back to the furry friends in need. Beyond my volunteer work, I'm hiking with my adopted pup or fostering animals awaiting their forever homes. In the heart of the city's animal community, my home is a sanctuary of love and compassion, where every wag of a tail brings joy and fulfillment.",
      important: "I have a chronic illness, so I would prefer a very clean roommate and to not have guests constantly over because I have a compromised immune system"
    },
    {
      name: 'John Bane',
      age: 46,
      isSmoker: true,
      hasPets: false,
      maxBudget: 2937,
      gender: 'male',
      image: 'https://images.unsplash.com/photo-1521119989659-a83eee488004?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjkxfHxyYW5kb20lMjBoaXNwYW5pYyUyMHBlb3BsZXxlbnwwfHwwfHx8MA%3D%3D',
      city: 'San Francisco',
      id: 21,
      bio: "Hello, I'm John, a fashionista crafting unique styles in the eclectic fashion scene of San Francisco. Beyond the runway, I'm exploring art galleries or dancing to live music in trendy venues. My studio is a canvas of creativity amidst the city's artistic spirit, where fabrics and colors intertwine to create fashion statements that reflect the vibrant energy of San Francisco.",
      important: "I work night shifts and need to sleep during the day so I would prefer someone that can be quiet during the day."
    },
    {
      name: 'Ava Wilson',
      age: 38,
      isSmoker: true,
      hasPets: true,
      maxBudget: 4550,
      gender: 'non-binary',
      image: 'https://images.unsplash.com/photo-1548142813-c348350df52b?q=80&w=2592&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 22,
      bio: "Hey, I'm Ava, a literature lover spinning tales in the charming neighborhoods of San Francisco. Beyond writing, I'm strolling through historic streets or sipping artisanal coffee in cozy cafes. In the comfort of my home office, books line the shelves, inspiring creativity and igniting imaginations with every turn of the page.",
      important: "My foot is currently broken so it is important to me to find a place with an elevator."
    },
    {
      name: 'Kya Smalls',
      age: 44,
      isSmoker: false,
      hasPets: false,
      maxBudget: 2039,
      gender: 'female',
      image: 'https://images.unsplash.com/photo-1484588168347-9d835bb09939?q=80&w=2187&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 23,
      bio: "Hello, I'm Kya, an animal lover volunteering at Denver's local shelters and rescues to give back to the furry friends in need. Beyond my volunteer work, I'm hiking with my adopted pup or fostering animals awaiting their forever homes. In the heart of the city's animal community, my home is a sanctuary of love and compassion, where every wag of a tail brings joy and fulfillment.",
      important: "I would much prefer a place that has a gym in unit and separate bathrooms if possible!"
    },
    {
      name: 'Shawna Willis',
      age: 50,
      isSmoker: false,
      hasPets: true,
      maxBudget: 2609,
      gender: 'female',
      image: 'https://images.unsplash.com/photo-1545133875-55b651cbf4aa?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 24,
      bio: "Hey, I'm Shawna, a marketing maven crafting compelling campaigns in the dynamic city of San Francisco. Beyond brainstorming sessions, I'm exploring cultural festivals or savoring gourmet cuisine in vibrant neighborhoods. In the heart of the city's creative pulse, my workspace is a hub of innovation, where ideas flow freely and brands come to life.",
      important: "I work night shifts and need to sleep during the day so I would prefer someone that can be quiet during the day."
    },
    {
      name: 'Kayla Joelle',
      age: 24,
      isSmoker: true,
      hasPets: true,
      maxBudget: 4284,
      gender: 'female',
      image: 'https://images.unsplash.com/photo-1525134479668-1bee5c7c6845?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 25,
      bio: "Greetings, I'm Sophia, a fitness enthusiast staying active amidst Denver's breathtaking landscapes. When I'm not hitting the trails, I'm practicing yoga in city parks or cycling along scenic routes. My home gym is a sanctuary of strength and resilience, where every workout fuels my passion for health and wellness in the Mile High City.",
      important: "I have a dog so I need a pet friendly building, or better yet, a place with a backyard. She is super sweet and well behaved and loves to play, just needs more space!"
    },
    {
      name: 'Danny Myers',
      age: 24,
      isSmoker: false,
      hasPets: true,
      maxBudget: 1077,
      gender: 'male',
      image: 'https://images.unsplash.com/photo-1633303628452-aba98113b73b?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 26,
      bio: "Hi, I'm Danny, a history buff delving into Denver's rich heritage and storied past. When I'm not visiting museums or historic sites, I'm attending cultural events or exploring vintage neighborhoods. In the heart of the Mile High City, my home office is a portal to the past, where every artifact and archive tells a tale of Denver's fascinating history.",
      important: "I have a chronic illness, so I would prefer a very clean roommate and to not have guests constantly over because I have a compromised immune system"
    },
    {
      name: 'Janice Wents',
      age: 31,
      isSmoker: true,
      hasPets: true,
      maxBudget: 3656,
      gender: 'non-binary',
      image: 'https://images.unsplash.com/photo-1625003460653-95a5e4a7ea01?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 27,
      bio: "Hey, I'm Janice, an outdoor adventurer exploring the boundless wilderness surrounding Denver. Beyond hiking and camping, I'm rock climbing in rugged canyons or whitewater rafting down rushing rivers. In the heart of Colorado's outdoor playground, my basecamp is a haven of adventure, where every expedition is an opportunity to connect with nature and push my limits.",
      important: "I work night shifts and need to sleep during the day so I would prefer someone that can be quiet during the day."
    },
    {
      name: 'Jane Wyle',
      age: 33,
      isSmoker: false,
      hasPets: true,
      maxBudget: 4541,
      gender: 'non-binary',
      image: 'https://images.unsplash.com/photo-1525060539736-979c838b7072?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 28,
      bio: "Hello, I'm Jane, a foodie indulging in Denver's diverse culinary scene one bite at a time. When I'm not dining out, I'm experimenting with recipes at home or exploring farmers' markets for fresh ingredients. In the heart of the Mile High City, my kitchen is a playground of flavors, where every dish is a culinary adventure waiting to be savored.",
      important: "I have a dog so I need a pet friendly building, or better yet, a place with a backyard. She is super sweet and well behaved and loves to play, just needs more space!"
    },
    {
      name: 'Johnna Jones',
      age: 29,
      isSmoker: false,
      hasPets: false,
      maxBudget: 4096,
      gender: 'non-binary',
      image: 'https://images.unsplash.com/photo-1502767882403-636aee14f873?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 29,
      bio: "Salutations, I'm Johnna, an animal advocate championing the rights of furry friends in the vibrant city of San Francisco. When I'm not rescuing animals, I'm hiking through urban parks or volunteering at local shelters. My workspace is a haven for animals in need amidst the city's hustle and bustle, where every bark and meow is met with compassion and care.",
      important: "I work near downtown, so I would prefer a place close to downtown or close to public transit."
    },
    {
      name: 'Harper Samms',
      age: 42,
      isSmoker: false,
      hasPets: true,
      maxBudget: 3121,
      gender: 'female',
      image: 'https://images.unsplash.com/photo-1523824921871-d6f1a15151f1?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 30,
      bio: "Greetings, I'm Harper, a history buff immersing myself in the rich heritage of San Francisco's historic districts. Beyond museum visits, I'm sipping artisanal cocktails in speakeasy bars or exploring hidden gems tucked away in the city's alleys. Amidst the whispers of history, my workspace is a portal to the past, where stories come alive and legends are born.",
      important: "I have a dog so I need a pet friendly building, or better yet, a place with a backyard. She is super sweet and well behaved and loves to play, just needs more space!"
    },
    {
      name: 'Hamish White',
      age: 25,
      isSmoker: false,
      hasPets: false,
      maxBudget: 1425,
      gender: 'male',
      image: 'https://images.unsplash.com/photo-1524666041070-9d87656c25bb?q=80&w=1587&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 31,
      bio: "Hi there, I'm Hamish, a culinary maestro infusing global flavors into the diverse culinary scene of San Francisco. When I'm not stirring pots in the kitchen, I'm exploring jazz clubs or savoring artisanal delicacies in local eateries. In the heart of the culinary capital, my workspace is a symphony of flavors, where culinary magic unfolds with each dish.",
      important: "I have a chronic illness, so I would prefer a very clean roommate and to not have guests constantly over because I have a compromised immune system"
    },
    {
      name: 'Sean Davis',
      age: 38,
      isSmoker: true,
      hasPets: false,
      maxBudget: 1866,
      gender: 'male',
      image: 'https://images.unsplash.com/photo-1595475038784-bbe439ff41e6?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 32,
      bio: "Hey there, I'm Sean, a nature lover embracing the rugged beauty of the Rocky Mountains from my home in Denver. When I'm not hitting the slopes, I'm hiking through scenic trails or camping beneath starry skies. My cozy cabin is a sanctuary amidst the majestic mountains, where every sunrise brings a new adventure and every sunset paints the sky in hues of gold.",
      important: "I work very early in the mornings, so I would like to live with someone who goes to bed early/is on a similar schedule so we don’t keep eachother up at night or wake each other up in the morning."
    },
    {
      name: 'Henry Taylor',
      age: 22,
      isSmoker: true,
      hasPets: true,
      maxBudget: 3544,
      gender: 'male',
      image: 'https://images.unsplash.com/photo-1544168190-79c17527004f?q=80&w=2832&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 33,
      bio: "Hello, I'm Henry, a foodie indulging in Denver's diverse culinary scene one bite at a time. When I'm not dining out, I'm experimenting with recipes at home or exploring farmers' markets for fresh ingredients. In the heart of the Mile High City, my kitchen is a playground of flavors, where every dish is a culinary adventure waiting to be savored.",
      important: "I have a dog so I need a pet friendly building, or better yet, a place with a backyard. She is super sweet and well behaved and loves to play, just needs more space!"
    },
    {
      name: 'Oliver Jones',
      age: 31,
      isSmoker: true,
      hasPets: false,
      maxBudget: 3710,
      gender: 'non-binary',
      image: 'https://images.unsplash.com/photo-1525748822304-6807cb1348ab?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 34,
      bio: "Hi, I'm Oliver, a music aficionado spreading rhythm and melody in the lively music scene of San Francisco. When I'm not strumming guitar chords, I'm exploring record stores or attending live performances in iconic venues. My studio is a symphony of sound amidst the city's cultural diversity, where melodies take shape and harmonies fill the air with musical magic.",
      important: "I would really prefer to live in the Marina to be closer to my job/friends, but I am open to Russian Hill or Cow Hollow!"
    },
    {
      name: 'Blair Montgomery',
      age: 30,
      isSmoker: false,
      hasPets: true,
      maxBudget: 3763,
      gender: 'non-binary',
      image: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 35,
      bio: "Greetings, I'm Blair, a fitness enthusiast staying active amidst Denver's breathtaking landscapes. When I'm not hitting the trails, I'm practicing yoga in city parks or cycling along scenic routes. My home gym is a sanctuary of strength and resilience, where every workout fuels my passion for health and wellness in the Mile High City.",
      important: "I am not fully able-bodied, so I prefer to have an apartment on the ground floor or with an elevator, and in a place with wheelchair accessibility."
    },
    {
      name: 'Andrea Walston',
      age: 48,
      isSmoker: false,
      hasPets: true,
      maxBudget: 2335,
      gender: 'non-binary',
      image: 'https://images.unsplash.com/photo-1573878593061-ed8c445d0af4?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 36,
      bio: "Hey, I'm Andrea (Andy for short), an outdoor adventurer exploring the boundless wilderness surrounding Denver. Beyond hiking and camping, I'm rock climbing in rugged canyons or whitewater rafting down rushing rivers. In the heart of Colorado's outdoor playground, my basecamp is a haven of adventure, where every expedition is an opportunity to connect with nature and push my limits.",
      important: "I would really prefer to live in the South Denver to be closer to my job/friends, but I am open to Cherry Creek or Union Station!"
    },
    {
      name: 'Georgia Monroe',
      age: 30,
      isSmoker: true,
      hasPets: false,
      maxBudget: 1932,
      gender: 'female',
      image: 'https://images.unsplash.com/photo-1485463598028-44d6c47bf23f?q=80&w=2849&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 37,
      bio: "Howdy, I'm Georgia, an environmentalist championing sustainability in the scenic landscapes of San Francisco. Beyond conservation efforts, I'm hiking through mountain trails or nurturing native plants in my backyard garden. My workspace is a sanctuary of green amidst the urban jungle, reflecting my commitment to preserving the natural beauty of our city.",
      important: "I work in Fidi so I would ideally like to live in one of the neighboring areas, or live somewhere walking distance to a BART station."
    },
    {
      name: 'Sophia Jackson',
      age: 50,
      isSmoker: true,
      hasPets: true,
      maxBudget: 4219,
      gender: 'female',
      image: 'https://images.unsplash.com/photo-1465429167186-266ef03d6277?q=80&w=2788&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 38,
      bio: "Greetings, I'm Sophia, a fitness enthusiast staying active amidst Denver's breathtaking landscapes. When I'm not hitting the trails, I'm practicing yoga in city parks or cycling along scenic routes. My home gym is a sanctuary of strength and resilience, where every workout fuels my passion for health and wellness in the Mile High City.",
      important: "I would really prefer to live in the South Denver to be closer to my job/friends, but I am open to Cherry Creek or Union Station!"
    },
    {
      name: 'Dolly Parson',
      age: 48,
      isSmoker: true,
      hasPets: true,
      maxBudget: 1713,
      gender: 'female',
      image: 'https://images.unsplash.com/photo-1615538785945-6625ccdb4b25?q=80&w=1287&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 39,
      bio: "Hello, I'm Dolly, a foodie indulging in Denver's diverse culinary scene one bite at a time. When I'm not dining out, I'm experimenting with recipes at home or exploring farmers' markets for fresh ingredients. In the heart of the Mile High City, my kitchen is a playground of flavors, where every dish is a culinary adventure waiting to be savored.",
      important: "I would really prefer to live in the South Denver to be closer to my job/friends, but I am open to Cherry Creek or Union Station!"
    },
    {
      name: 'Chloe Taylor',
      age: 29,
      isSmoker: true,
      hasPets: true,
      maxBudget: 3356,
      gender: 'female',
      image: 'https://images.unsplash.com/photo-1498551172505-8ee7ad69f235?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 40,
      bio: "Hey, I'm Chloe, a marketing maven crafting compelling campaigns in the dynamic city of San Francisco. Beyond brainstorming sessions, I'm exploring cultural festivals or savoring gourmet cuisine in vibrant neighborhoods. In the heart of the city's creative pulse, my workspace is a hub of innovation, where ideas flow freely and brands come to life.",
      important: "I would really prefer to live in the Marina to be closer to my job/friends, but I am open to Russian Hill or Cow Hollow!"
    },
    {
      name: 'Whitney Winter',
      age: 43,
      isSmoker: false,
      hasPets: true,
      maxBudget: 2464,
      gender: 'female',
      image: 'https://images.unsplash.com/photo-1450297350677-623de575f31c?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 41,
      bio: "Hi, I'm Whitney, an aspiring artist capturing the vibrant colors of Denver's urban landscape on canvas. Beyond my studio, I'm exploring art districts or attending gallery openings to soak in the city's creative energy. In the heart of Denver's art scene, my workspace is a canvas of possibilities, where every brushstroke tells a story of inspiration and imagination.",
      important: "I work near downtown, so I would prefer a place close to downtown or close to public transit."
    },
    {
      name: 'Lyle Cranston',
      age: 27,
      isSmoker: false,
      hasPets: false,
      maxBudget: 1388,
      gender: 'male',
      image: 'https://images.unsplash.com/photo-1597969892064-a7b26a98c335?q=80&w=1587&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 42,
      bio: "Howdy, I'm Lyle, an environmentalist championing sustainability in the scenic landscapes of San Francisco. Beyond conservation efforts, I'm hiking through mountain trails or nurturing native plants in my backyard garden. My workspace is a sanctuary of green amidst the urban jungle, reflecting my commitment to preserving the natural beauty of our city.",
      important: "I work in Fidi so I would ideally like to live in one of the neighboring areas, or live somewhere walking distance to a BART station."
    },
    {
      name: 'Maxwell Puller',
      age: 22,
      isSmoker: true,
      hasPets: true,
      maxBudget: 3711,
      gender: 'male',
      image: 'https://images.unsplash.com/photo-1528900403525-dc523d4f18d6?q=80&w=1888&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 43,
      bio: "Hello, I'm Max but people usually call me by my last name, Jackson. I'm a foodie indulging in Denver's diverse culinary scene one bite at a time. When I'm not dining out, I'm experimenting with recipes at home or exploring farmers' markets for fresh ingredients. In the heart of the Mile High City, my kitchen is a playground of flavors, where every dish is a culinary adventure waiting to be savored.",
      important: "I have a dog that is extremely shy, so I need to live with someone that doesn’t constantly have guests over."
    },
    {
      name: 'Lucas Davis',
      age: 25,
      isSmoker: true,
      hasPets: true,
      maxBudget: 1490,
      gender: 'male',
      image: 'https://images.unsplash.com/photo-1542909193-dc7943084747?q=80&w=1888&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 44,
      bio: "What's up, I'm Lucas, an adventure seeker exploring the rugged terrain of the Pacific Northwest from my home base in San Francisco. When I'm not scaling mountains, I'm kayaking through picturesque bays or camping beneath starlit skies. My workspace is wherever the trail leads, a testament to the boundless spirit of exploration that drives me forward.",
      important: "I have a dog that is extremely shy, so I need to live with someone that doesn’t constantly have guests over."
      },
      {
      name: 'Noah Duvall',
      age: 24,
      isSmoker: false,
      hasPets: false,
      maxBudget: 2298,
      gender: 'male',
      image: 'https://images.unsplash.com/photo-1503443207922-dff7d543fd0e?q=80&w=1827&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 45,
      bio: "Salutations, I'm Noah, an animal advocate championing the rights of furry friends in the vibrant city of San Francisco. When I'm not rescuing animals, I'm hiking through urban parks or volunteering at local shelters. My workspace is a haven for animals in need amidst the city's hustle and bustle, where every bark and meow is met with compassion and care.",
      important: "I would really prefer to live in the Marina to be closer to my job/friends, but I am open to Russian Hill or Cow Hollow!"
      },
      {
      name: 'Liam Jones',
      age: 49,
      isSmoker: false,
      hasPets: false,
      maxBudget: 4070,
      gender: 'male',
      image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 46,
      bio: "Hey there, I'm Liam, a nature lover embracing the rugged beauty of the Rocky Mountains from my home in Denver. When I'm not hitting the slopes, I'm hiking through scenic trails or camping beneath starry skies. My cozy cabin is a sanctuary amidst the majestic mountains, where every sunrise brings a new adventure and every sunset paints the sky in hues of gold.",
      important: "I work near downtown, so I would prefer a place close to downtown or close to public transit."
      },
      {
      name: 'Charlotte Salatal',
      age: 23,
      isSmoker: false,
      hasPets: false,
      maxBudget: 1802,
      gender: 'female',
      image: 'https://images.unsplash.com/photo-1542596768-5d1d21f1cf98?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'Denver',
      id: 47,
      bio: "Hi, I'm Charlotte, an aspiring artist capturing the vibrant colors of Denver's urban landscape on canvas. Beyond my studio, I'm exploring art districts or attending gallery openings to soak in the city's creative energy. In the heart of Denver's art scene, my workspace is a canvas of possibilities, where every brushstroke tells a story of inspiration and imagination.",
      important: "I am not fully able-bodied, so I prefer to have an apartment on the ground floor or with an elevator, and in a place with wheelchair accessibility."
      },
      {
      name: 'Daniel Blue',
      age: 32,
      isSmoker: false,
      hasPets: true,
      maxBudget: 2255,
      gender: 'male',
      image: 'https://images.unsplash.com/photo-1542611660-288050adc7d1?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 48,
      bio: "Hi there, I'm Daniel, a culinary maestro infusing global flavors into the diverse culinary scene of San Francisco. When I'm not stirring pots in the kitchen, I'm exploring jazz clubs or savoring artisanal delicacies in local eateries. In the heart of the culinary capital, my workspace is a symphony of flavors, where culinary magic unfolds with each dish.",
      important: "I work in Fidi so I would ideally like to live in one of the neighboring areas, or live somewhere walking distance to a BART station."
      },
      {
      name: 'Benjamin Button',
      age: 25,
      isSmoker: false,
      hasPets: true,
      maxBudget: 1177,
      gender: 'male',
      image: 'https://images.unsplash.com/photo-1523327114837-8d125518bf65?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      city: 'San Francisco',
      id: 49,
      bio: "Hello, I'm Benjamin, a coffee connoisseur brewing perfection in the cozy cafes of San Francisco. When I'm not roasting beans, I'm exploring local markets or hiking through lush green parks. In the heart of the coffee capital, my workspace is a sanctuary of aroma, where every cup tells a story of passion and craftsmanship.",
      important: "I have a dog that is extremely shy, so I need to live with someone that doesn’t constantly have guests over."
      },
      {
      name: 'Ethan Taylor',
      age: 33,
      isSmoker: true,
      hasPets: true,
      maxBudget: 3493,
      gender: 'male',
      image: 'https://images.pexels.com/photos/7289305/pexels-photo-7289305.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      city: 'San Francisco',
      id: 50,
      bio: "Greetings, I'm Ethan, a legal eagle advocating for justice in the vibrant streets of San Francisco. When I'm not poring over case files, I'm exploring the city's historic landmarks or unwinding with a game of chess in the park. My office is a bastion of order amidst the urban chaos, where every brief is meticulously crafted to defend the rights of the vulnerable.",
      important: "I am not fully able-bodied, so I prefer to have an apartment on the ground floor or with an elevator, and in a place with wheelchair accessibility."
      }
     ]

module.exports = roommateData; 